### ISSUE TITLE
Where can I find your paper?

### ISSUE THREAD

**Issue by godlin-sjtu** [xiaofang007/ViP#1]
Hi there, 

That's great work, can you send me a link to check your paper?

Thanks!

**Comment by xiaofang007** [comment]
Hi, I am sorry that the paper has not been released yet, but you might find a short version here https://hkustsmartlab.github.io/2024/07/26/vip/

**Comment by godlin-sjtu** [comment]
Thanks for your reply. I will read it.

**Comment by xiaofang007** [comment]
Hi, we have uploaded our paper in https://arxiv.org/pdf/2409.00341

**Comment by godlin-sjtu** [comment]
Nice work，many thanks.


-----原始邮件-----
发件人: FANG ***@***.***>
目标语言: xiaofang007 ***@***.***>
抄送: godlin-sjtu ***@***.***>; State ***@***.***>
日期: 2024年9月4日星期三 21:58 CST
主题: Re: [xiaofang007/ViP] Where can I find your paper? (Issue #1)


Hi, we have uploaded our paper in https://arxiv.org/pdf/2409.00341
