### ISSUE TITLE
About the supervised methods in result comparisons

### ISSUE THREAD

**Issue by TianBaoGe** [xiaofang007/ViP#10]
In Table 1 of the paper, what are the supervised methods involved?

**Comment by xiaofang007** [comment]
Hi, sorry for the confusion. Supervised methods are the average of three vision backbones, i.e. ViT-B/16, ViT-L/14 and ResNet-50 training from scratch.

**Comment by TianBaoGe** [comment]
> Hi, sorry for the confusion. Supervised methods are the average of three vision backbones, i.e. ViT-B/16, ViT-L/14 and ResNet-50 training from scratch.

THX! I got it.

**Comment by TianBaoGe** [comment]
> Hi, sorry for the confusion. Supervised methods are the average of three vision backbones, i.e. ViT-B/16, ViT-L/14 and ResNet-50 training from scratch.

THX! I got it.

**Comment by TianBaoGe** [comment]
Dear author, could you please clarify what the initialization for the three different backbones is during training from scratch? Are they initialized with CLIP weights? Also, I assume that the supervised classification accuracy on the Pneumonia dataset should easily exceed 90%, correct?
