### ISSUE TITLE
Unable to search for your papers

### ISSUE THREAD

**Issue by 1Shuangjiang1** [xiaofang007/ViP#3]
Your work is great, but I can't find your paper on Google. Can you give me the link to your paper? I would like to further understand the details of the paper

**Comment by xiaofang007** [comment]
Hi, I am sorry that that the paper has not been released yet. You may refer to issue #1.

**Comment by xiaofang007** [comment]
Hi, we have uploaded our paper in https://arxiv.org/pdf/2409.00341
