### ISSUE TITLE
how to try my own dataset on your work？

### ISSUE THREAD

**Issue by 1Shuangjiang1** [xiaofang007/ViP#4]
Hello author, thank you for sharing your great work. I would like to try my own dataset on your work. I have already organized the dataset according to the examples in the readme and created descriptions for each category. **Before proceeding, I wanted to ask if there are any additional modifications or steps I need to consider before starting the training process. Is it possible to begin training directly using the provided commands in the README?**

Your guidance would be greatly appreciated! Thank you again for your time and for sharing your work.

**Comment by xiaofang007** [comment]
Hi, thanks for your interest. I think you can directly train if you have modified the data folder in the training script. There is no need to modify the ViP trainer.
